### ISSUE TITLE
Non-modding related suggestion: Minecraft space RP server thing

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#121]
Hello WarpDrive devs and community, this is your fellow minecrafter Marvin Megavolt here,
I am working on creating a modpack and corresponding server called MineGalaxy. It's a space RP-type server where players can join different factions and nations, play as different alien races, participate in active commerce, politics, warfare and much much more. The important bit to mention here though is that the cornerstone mod of this pack is going to be WarpDrive, and considering that, I hereby suggest that we (the WarpDrive team and community and the MineGalaxy team) collaborate on this project, and perhaps even put MineGalaxy as the official server for WarpDrive.

Here: 
https://drive.google.com/folderview?id=0B-iAs6Eh0N1IWnd1R051amJIaGc&usp=sharing
is a link to the Google Drive folder that currently contains the project information for the pack. I'll note here that we neither have a server nor a pack yet, as the pack is still in development.

**Comment by TheNumenorean** [comment]
I very much like the premise of your server, it sound like it could be quite interesting. In what way are you suggesting we help outside of the continued development of WarpDrive?

Personally, I strongly oppose having "official servers" for mods, since it frankly does not make any logical sense excepting as advertisement for the server.

**Comment by CaptainMegavolt** [comment]
I suppose you have apoint of the official server thing. What I mostly ment by that was that we could have an official test world for new versions of warpdrive or something like that. IDK, it just seemed like there could be good that would come of it.

On the help situation, I will need to get back to you on that one. Not that I don't know how I would like you to help, just that I am posting this at school and do not have much time on my hands.

**Comment by LemADEC** [comment]
Your server setup is pretty close to what we're trying to achieve on my WorldWarMinecraft pack. Sadly, I can't develop modpack and maintaining the mod at the same time.

Regarding your mods list:
- GregTech is not raiding friendly. It adds lots of tiers that makes it too hard to come back after being raided. You have to be very careful on your tiers and especially, how easy is it to get started/recover. RotaryCraft suffers from the same issue (interresting but complicated setup for PvP).
- I'm a bit confused with wall climbing mod when space already works with jetpacks and such.
- power source without fuel, like solar panels, needs careful consideration. Notably, when you can put a huge amount of power source in a single block like Advanced Solar Panel and no fuel (like an IC2 Nuclear reactor). Crafting cost won't stop the players, especially when more solars give faster access to crafting more solars with no external resources (Solar -> MassFab -> more Solar).
- MatterOverdrive will break your balance. It's not meant for PvP, from both player fights and resources collection. Same goes with RF Tools or Mystcraft which provides infinite resources: players have no reason to explore new areas or raid the ennemy. IC2 MassFab and AS Assembler are more balanced but it's pretty much the same infinite resources issue.
- you don't want multiple tech mods in the pack. Choose a theme, pick a tech mod and stick with it. OK, maybe 2 that actually complement each others like IC2 + BuildCraft. I would advise EnderIO for balance or Mekanism by popular request (but your server will hate Mekanism).
- AE2 breaks your ship cargo. It gives infinite storage in a single block (or so). Hence, you've no reason to increase your ship (and it's fuel/maintenance costs) to transport more stuff. We could balance it at the mod level, to some point (increase weight depending on block content instead of just counting blocks). Same goes with portable chests, huge backpacks and similar items.
- logistic pipes and Pneumaticraft will lag your server, also they are not Warp friendly.
- Flan is nice and cute but buggy and unbalanced, use at your own risk :p.
- I remember some nasty dup bugs with Sync. It's a pain to handle for server admins.
- who said ICBM conflicts with WarpDrive?
- Carpenter's block will lag your client. You want to add textures variations, but certainly not tile entities.
- Lanteacraft and related portals defeat the purpose of ships and warp

**Comment by CaptainMegavolt** [comment]
Thanks for all the tips! For starters, many of the mods on that list are only tentative ideas. And I have no idea who said ICBM conflicts with warpdrive, since it does not. As you can see, MineTweaker is on the mods list, and I planned to rework absolutely everything with it, making all the different mods interdependent, and disabling any cheaty, bugged, or other problem content. 

RFtools is in there as a means to create custom planets; all dimension-creation stuff is disabled for survival players.

I thought ICBM was not up-to-date for 1.7.10?

LanteaCraft has already been vetoed, it just is not off the list yet. If any similar portal mod were used, it would be limited to very short range or some such thing, or be restricted to admins only.

PneumatiCraft is probably not necessary, and logistics pipes... I don't know. If you say it is laggy I will remove it.

Carpenters blocks... if you say so. Never had any problems with them myself.

AE2 was going to get a huge reorganization with Minetweaker.

Matter Overdrive was similarly going to get heavily Minetweaked.

Mass Fabricators are completely disabled.

I'll have to think about the solar panel thing...

GregTech will probably not be in the pack, as it always crashes for seemingly no reason; and even if it were, it would be minetweaked.

Smart Moving is just there for immersion and a new aspect of PvP and similar stuff. It's not like there aren't jetpacks, but remember that this is not _just_ a space pack.

EnderIO will almost certainly never be in the pack, due to its theme and style not fitting the theme of the server (in a way that cannot exactly just be Minetweaked away). Mekanism however is going to be a main mod in the pack. I will actually probably remove the Thermal Series in favor of Mekanism.

Flan's Mod may be unbalanced to begin with, but I will be Minetweaking it heavily, so that its recipes are built inside of NuclearCraft's heavy workspace or some such thing... Perhaps Avarita's Extreme Crafting Table...

What is the AS assembler?

**Comment by TheNumenorean** [comment]
Disabling mass fabs means you cannot use the standard WD recipes notably. Unless you want there to be one ship in the entire world.

Advanced Solar

IN fairness, dense AE2 storage is inordinately expensive.

There is no worthwhile ICBM for 1.7.10

I am too busy with college to develop right now, and wont be back until summer, so if lemADEC is busy too im afraid we wont be much help.

**Comment by LemADEC** [comment]
In 3 years, I've only got 1 crash with Gregtech. So I'm quite surprise with your statement :).
I've yet to use Mekanism on my server without experimenting a couple crashing bug or extreme lag within the first week.

Increasing the recipes cost will not solve the related exploit. Once a player has infinite resources or an OP weapon, he/she'll use it. You'll need to at least change the fuel cost or nerf the maximum damage.

AtomicScience Assembler allows to create items from antimatter.

**Comment by CaptainMegavolt** [comment]
Nono, I mean GregTech crashes with other mods in my pack. Sorry to confuse
you.

**Comment by CaptainMegavolt** [comment]
Oh oops excuse me, my antivirus is sticking stupid 'this email has been sent from a virus free computer' thingies in my email.

**Comment by CaptainMegavolt** [comment]
I am not using AtomicScience as it is not up to date for 1.7.10, and I plan to remove or reconfigure all OP things ,not just change the recipes. And I am not neccessarily making the recipes much more expensive. I am just making the different mods interdependent, and rebalancing stuff for the mechanics of the server.

**Comment by LemADEC** [comment]
AtomicScience was just an example.

**Comment by CaptainMegavolt** [comment]
Gotcha

**Comment by LemADEC** [comment]
This not an WarpDrive issue. Open separate tickets if you need fixes or request new features.
