### ISSUE TITLE
"Not enough space for jump" message is ambiguous

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#174]
For some reason, WarpDrive says cant jump into claimed land due to "Not enough space for jump".
The same occurs when the ship is trying to jump out of territory that is claimed.
I see the message your trying to send and it is not working :( (Protected Area reference).

**Comment by LemADEC** [comment]
The navigation controller try to find another spot for the ship, outside the protected area. If you're too close to it, it'll cancel the jump reporting "not enough space for jump" since it can't find a spot for the ship.
We could explain the message that it might be due to obstacles or protected area but going further would make it overcomplicated

**Comment by LemADEC** [comment]
This is fixed in next update
