### ISSUE TITLE
Crash with 1.3.27

### ISSUE THREAD

**Issue by axelpx** [LemADEC/WarpDrive#205]
Hello,

Server crash at start-up on Thermos 1.7.10-1614.55 with mod version 1.3.27.

Version 1.3.22 works just fine.

Error:
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cr0s/warpdrive/block/TileEntityLaser

Full crash log: http://pastebin.com/qFvfWSKc

Thanks for working on this mod!

**Comment by LemADEC** [comment]
The issue is in the farseek mod as found in the crash report:

```
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
    at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
    at farseek.core.SuperCallFixingMethodVisitor.visitMethodInsn(MethodReplacementTransformer.scala:43)
```

Farseek is required for Streams and Repose mods which are both missing in your list. Are you sure you need that library?

Also, try updating your Thermos libraries or update to a more recent version like Thermos-1.7.10-1614.57 which works just fine for us and WarpDrive 1.3.28.

**Comment by axelpx** [comment]
Thanks a lot :)
