### ISSUE TITLE
Allow lasers to be controlled through laser mediums 

### ISSUE THREAD

**Issue by coolman1324** [LemADEC/WarpDrive#219]
Allow lasers to have there lua scripts controlled with there mediums

**Comment by LemADEC** [comment]
We've tried that but it's incompatible with OpenComputers by design of the latest.

**Comment by coolman1324** [comment]
I'm not sure if you understand what I'm saying, I'm thinking the medium has additional Luna commands in order to then control the laser. Like this:

m = peripheral.wrap("left")
x = m.laserPosition() --gets pos of laser
m.laserEmitBeam(1,1,3) -- laser fire there

**Comment by coolman1324** [comment]
Lua*

**Comment by LemADEC** [comment]
OpenComputers automatically network adjacent blocks. Adding LUA supports to laser medium means you require a full server rack to control a single laser.

That being said, it's unpractical to have to wire on the laser head and gives some bulky ship designs. So, we'll have to add some laser controller/mirror on the multi block to workaround that since Laser Mediums aren't an option.
