### ISSUE TITLE
[Wiki] Beacons?

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#237]
In the ComputerCraft Interface, beacons are mentioned, but there is no information on them in the Wiki. Could a stub be made with some basic details on them? I would be happy to play around with them and expand the Wiki, but I have no idea where to start from.

**Comment by Echo343** [comment]
From looking in the code, a beacon is a ship controller that a player entity is standing on top of.  When a ship jumps to a beacon, it will line up the x and z coordinates but will keep its existing y coordinate.  For this reason, when a ship jumps to a beacon, it is useful to be sure the jumping ship is at an appropriate height before the jump.

**Comment by LemADEC** [comment]
This feature will be redesigned in 1.10+, hence it was left undocumented

**Comment by khionu** [comment]
May I ask how much development you plan to do? This is a fairly old mod, and the number of incomplete features was disheartening. I stopped opening issues after a certain point, and stopped trying to build my pack after a later one :/

**Comment by LemADEC** [comment]
As announced on the forum, the next update will come with the next season of my modpack, hopefully in a few weeks.
We can't fix issues that aren't reported.

**Comment by LemADEC** [comment]
Beacon shouldn't be enabled by a player standing on top of block, even less an unrelated block. From lore perspective, a beacon shall be a specific block; it shall always be on through power and an 'enable' switch.
Beacon allow to define a target to navigate automatically too. For that we need the navigation block which will come at some point, probably with the ship tiers since they both implies LUA changes.

I've fixed the code back in 1.6.4, never tested it in 1.7.10. Feel tree to test it.

**Comment by LemADEC** [comment]
This is already in the roadmap
