### ISSUE TITLE
Ship unable to jump due to being snagged by Computer?

### ISSUE THREAD

**Issue by comus777** [LemADEC/WarpDrive#249]
![2017-03-24_12 03 55](https://cloud.githubusercontent.com/assets/25848267/24280259/1656edf4-108a-11e7-8e9e-ba2a87899d2a.png)
For some reason upon attempting to jump I get an error telling me that the ship is unable to jump due to the very computer that I need to interface with it. What is wrong with this thing?

**Comment by Adkkid** [comment]
Your dimensions are not relative to the way you placed the block. The controller itself defines the "front" of the ship, when placed adjacent to the core. Re-set your dimensions by pressing "D", and assume that the front of the ship will be left, going off the way you're facing right now.

**Comment by comus777** [comment]
So I have to calculate the ship's dimensions based off of the controller rather than the core? 

What about about that bit with the facing? How does that work?

**Comment by Adkkid** [comment]
Sorry...  I didn't explain it too well. Your core is the center of the ship, and the block you base the dimensions off of. But the "front" is whichever side you placed the controller on. In this case, the 'front' of your ship is actually to the left, since thats where you placed the controller. To be specific, if you didn't move the ship core or controller, your dimensions would look like this:
Front 4, Right 1, Back 2, Down 1, Up 3, and left however many are behind you.  

Keep in mind that when the ship is functional, all directions are relative to the way the ship is "facing". Use this to help setup if you need it. https://github.com/LemADEC/WarpDrive/wiki/Getting-Started:-Part-One,-The-Basics

**Comment by comus777** [comment]
Changed the dimensions a bit according to your directions and I'm in space now. Thanks!
