### ISSUE TITLE
Picking up stray blocks

### ISSUE THREAD

**Issue by AndrewSenapatiratne** [LemADEC/WarpDrive#251]
I noticed one big issue that is going to prevent me from using this in my mod pack. If you jump the ship so that a block that is not part of your ship is within the dimensions of the ship then jump again, these new blocks will come with you.

**Comment by LemADEC** [comment]
Ships are defined as cuboid regions.
Jump sequencer is inconsistent in that it allows to enter an area containing blocks but doesn't leave them behind.
It's more a fun factor than an annoyance since protected areas are cuboid, you won't be able to grief with that.

It's part of our roadmap to support 'freeform' ships.

**Comment by LemADEC** [comment]
see #29
