### ISSUE TITLE
12 suggestions, 5 problems

### ISSUE THREAD

**Issue by JohnNemECis** [LemADEC/WarpDrive#281]
Dear creators of this mod. This mod is Amazing, but there are many gaps, bugs and issues that almost make me cry. Here come a few examples

This mod is so amazing.  I think you guys should make it to be able to be a Stand-Alone mod. All that: This and This mod is required is so frustrating. For example: Computercraft and OpenComputers both don't have the elegancy of all the blocks you guys have added. A furturistic UI would look so good at this mod. Before i will speak in issues, I will give some suggestions if you guys make it a stand-alone mod:
1. The Ship Core: Instead of relying on other computers, you guys should maybe make a 3D interface in thich a player goes to something like spectator mode and gets instructions with beacon lights to select the dimension (I mean a straight line piercing all blocks not damaging them, so you can easy find where the line is, and never miss a block of your ship). 
2. The Ship controller: In this console I'd love to see a UI that shows who the captain is, and what the crew is, in a fashion of Star Trek( console with names, when selecting one seeing how he looks, when last signed on, and other stuff that could be seen important). Maybe it  would look better that you can connect a ship controller with the ship core by putting them in a **Connector** ( a work bench that is surrounded with Network blocks in an furnace-like shape). This would also have a button in which you can set a course ( showing a minimap for a preview of the destination. The way to change the steps in the same way like computercraft, but still on the minimap, layout editable in settings)
3. Lasers, Weapon controller, and Monitors:
The way lasers are built is beautifull. but even prettier would be if we didnt need a few thousand cables. If weapon controlers would be connected with lasers trough a connector, or something like that (see suggestion 2) it would stop the cable mess. In this, you can connect laser+camera, and setup batteries(still, with an interface that you can see the location of them in startup of the surroundings, so they can be set easely on differrent cams, telling them what camera would be the targetting laser, and still be able to tell them to still respond on another if wanted this way) Monitors I'd like to see the same, though a better range would be advised by me, or if you guys like the idea, intergrate it with the weapon controller, and let it not have all these different channels( maybe an weapon controller update?)
4. Cloaking core UI that shows how to build it, what is missing, if able to activate set mode menu, and when active, giving you a buff when in range which is visible for the player: cloaked
5. Energy conduits, and powercells, however you want them, and if possible, add a config so players can edit it to their needs
6. Endemorfic generator: can you rename it to something more easy like **'reactor core'**, and let the process be started when all hooked up, and when pressed right mouse button on core to be customized?
7. Transporter: an UI that has a minimap( range 1000blocks north, south east, west), scale 1:50, same accuracy, unless beam up: selecting a grid, between dimensional tp if in range of planet, your coords for middle point of grid. when area selected, select player name, time before beam up: 1/25th of the players height difference between teleporter pad and player.
8. radar: powersource, and subspace scanner needed, nothing more and nothing less needed, sonarlike mapping, no details, but more furturistic. the higher tier subspace scanner, the better location visibility, add ability to upgrade availible for minimap UI
9. **Messaging controller** : subspace scanner needed, possability to chat with nearby ships;
10. **View screen** : big brother of the monitor, but always active, viewing angle selectable when rightclicking it, box shape with selection tab front, back left, right, bottom, up. 
11. Item descriptions ingame. 
12. better way for forcefields: same way like putting up dimensions of ship, still upgradeable

Now the issues
1. When i build a ship at my Space Station, I cant travel to Space. I get the error message 'No planet defined' . (most recent version crashed while reaching space)

2. I also have an issue when using camera's. When i placed them down first, all went well. I had a perspective of like i was the camera. Now i have the issue that when i use a monitor, i see it like im standing on it. This annoys me, because the lasers can explode when hit, and so i have them surrounded with a hull whenever i can, and now I have to leave them volnurable. (latest version problem changes to that im stuck in a view that i see the inner block of the camera)

3. Galacticacraft also has mars as a main part, so i'd like to ask if you guys could add it to the space dimension. Its useless without them, as for on my pc, when i reach space, i dont see anything around. Its completely empty because of it.

4. There is also an add-ons for Galacticacraft that adds many planets. if you guys want to add them to supported, i'd be pleased.

5. Last of all, can you guys either change how many blocks a ship can maximally have to travel in a planet, because 3000 is way less than most ships are. I can't travel in a dimension when I have more, even when i dont reach any planet limits. if jumps would crash the game, make it movement. 

Can you guys please fix it? i really love this mod

**Comment by JohnNemECis** [comment]
quick note: im not sure if all problems i had still exist at the new beta

**Comment by LemADEC** [comment]
ok, that's a lot of question to address in a single issue.
What version of the mod are you using when having those issues?

Suggestion 1: OC and CC can already make custom HUDs to control your ship.
The mod is intended to allow you to make your own ship mainframe.
Some servers even propose their own custom scripts.

Suggestion 2: you can already manage your crew in there. I'm not sure what you mean with connector. Seems like a different suggestion of sort.

Suggestion 3: sounds like you have a very specific idea in mind, but I can't quite comprehend what you mean.
Wiring is part your ship design.
Laser cannon will change in the future to control them from back, so we don't double wiring side by side with laser mediums.

Suggestion 4: try the latest version, the status message have been updated.

Suggestion 5: there's already subspace capacitors.
Void conduit are part of the roadmap but will require conversion blocks.
There's already 5+ mods with energy transportation around, so it's not a priority for us.

Suggestion 6: Enantiomorphic reactor is named to its lore as Reactor core is ambiguous with the Warp core block.
It's a no-fuel selfsustained energy source. It's balanced by requiring constant monitoring.
Sounds like you're proposing a creative energy reactor, or did I misunderstood your suggestion?

Suggestions 7 and 8: seems like you were taking notes, my english is too limited to understand what you mean here.
Transporter has no recipes because it can be exploited/abused in SMP. It'll be updated with tiers once we fix the exploit.
Radar internal structures are in test phase. Once stable, there'll be 3 tiers for local/entity scanning, vs orbital scanning vs deep space.

Suggestion 9: CC and OC already have wireless networking. Reinventing CC/OC is not a priority for us.

Suggestion 10: each view screen will directly impact your FPS. 1 screen -> half the FPS, 4 screen -> 1/5th of the FPS. You can try it with SecurityCraft and LookingGlass.

Suggestion 11: which items are you talking about? which description?

Suggestion 12: the projector is a design constrains for gameplay balance. It's also intended for localized damages on your ship/station.
You can already arrange the dimensions to your liking with the translation and scaling upgrades.
We're experimenting with a 'preview' overlay on the ship core. Once it's stable, it'll be applied to the cloaking core and forcefield projector.

Issues 1 and 2: you're probably using an old version

Issue 3 and 4: that's in the roadmap. You can use MystCraft or Multiworld to create your own for now. GC planets can also be used, to some extent.

Issue 5: ship mass constrains are a configuration option.
In creative mode, we've players doing 200 to 800 m long ships.
In survival mode, it's fairly expensive to build a ship of 3k blocks by itself.

**Comment by JohnNemECis** [comment]
Thanks for the quick reply. NOTE: I was using an old version. im now using the latest.

About suggestion 9. I actually ment a machine that is like star trek used for placing messages in the kind of automated distress calls, long range messaging between ships, private communication with another ship et cetera.

Issue 1 has changed from no travel possible to imminent shutdown, server closed message.
Issue 2 persists in old-fashion. i can see trough it, but i look to the guts of the main block

**Comment by LemADEC** [comment]
Suggestion 9: beacons are in the roadmap for labelling areas in space. For messaging itself, refer to #284 

Issue 1: are you building your ship in the overworld within it's world border? if that's case, we'll need your logs.

Issue 2: there's an intermittent rendering bug that shows the interior of the block while it shouldn't. Probably caused by another mod hacking the render ids, couldn't reproduce it in dev so far.

**Comment by JohnNemECis** [comment]
I see someone has said issue 9 in an easier way (#284)

maybe i should just close this one and disect it in all different issues?

**Comment by LemADEC** [comment]
yes, it's much easier to handle issues separately
