### ISSUE TITLE
Feature request: More intelligent radars

### ISSUE THREAD

**Issue by JohnNemECis** [LemADEC/WarpDrive#287]
The radars now are... quite worthless, rubbish, and quite irresponsive. i'd  like to request a new kind. I'd love to see that the Radar relies on a subspace scanner and a ship scanner. maybe you could add that (range infinite as standard) every subspace scanner tier stands for accuracy. and than like 4 tiers, with an addition of upgrades, like for forcefields. in this way, you could have 20 different types, by adding 5 types of upgrades. starting off with an accuracy of : lowest tier: 5 grids (a grid is something like 1km x 1 km) accuracy, random generated pattern so you cant find exact location of the grid, but still close to each other.
highest tier ( maybe a need of a dragonegg in crafting recepy to make it not easy acces) and than a accuracy of 50 blocks. This would require cursor accuracy to find a coord

**Comment by LemADEC** [comment]
The existing radar is fairly OP on our PvP server and we had to nerf its range because players got raided too easily because of it.
The scan delay is there to reduce server lag and gives some realistic touch.

The current plan is to have 3 tiers of radars with different ranges and scanning capabilities, already explained in the forum if my memory serves right.
Imprecision is effectively in the plan. We still need to decide on where to account for it so players can't bypass it too easily. Minimum inaccuracy would be 64 blocks or x% of range.
Eventually, we'll add celestial object obscuration, if we can't find an efficient algorithm for it.

For the blocks themselves, I'm looking for something more multi block with antenna relays to boost precision. It's more realistic and avoid the microship that could scan the whole universe.

I'm a bit confused with the upgrade system you're proposing.

**Comment by LemADEC** [comment]
@JohnNemECis any update on this?

**Comment by LemADEC** [comment]
Radar upgrade is covered in #67
