### ISSUE TITLE
Your next update will include

### ISSUE THREAD

**Issue by Garr890354839** [LemADEC/WarpDrive#318]
In-game documentation, and LUA disc drives for ComputerCraft OR your own computer system, with GUI's for everything. I just had an Enantiomorphic reactor blow up on me, and powerful enough to destroy BEDROCK. IC2's Nuclear reactor is SO easy to maintain compared to that... explosive.

**Comment by LemADEC** [comment]
Wiki is fairly up to date, there's also a few videos linked in the Curse page.

LUA scripts are already preloaded, there's no point to add LUA disk drives.

Enantiormorphic reactor produce up to 70kRF/t, that's 20 times more than your top tier automatic IC2 reactor.
Enantiormorphic reactor is matter/antimatter based, as such the explosion breaks the antimatter containment, which in turns removes random blocks in close range. For comparison, an IC2 reactor will remove all blocks in close range and affect up to 30+ m away from the core. As such, an exploding IC2 reactor is way more dangerous.

CC/OC are fairly unstables with random LUA crashes. Next update already removed the loop control from the LUA due to those repeated issues.

**Comment by LemADEC** [comment]
no answer, assuming closed

**Comment by Garr890354839** [comment]
Sorry for the late response, I don't know what the files are named.

Marx Wrath and 0^2
the first one sent this


Remember 9/11 with this very code:
<a target="_blank" href="
https://www.google.com/calendar/event?action=TEMPLATE&tmeid=NmtkNGphODc4b3RtMmRhcGRuYTV1ZmtrZTAgdGhlY2hvc2Vuc3RuZWtpcmJ5bWFzdGVyQG0&tmsrc=thechosenstnekirbymaster%40gmail.com"><img
border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif
"></a>
