### ISSUE TITLE
Ability to fully disable world border checks

### ISSUE THREAD

**Issue by Sirse** [LemADEC/WarpDrive#340]
In modded (like Cauldron) server world border checks are performed by inbuilt tools and WarpDrive checks are useless. Can you add the config option to disable checking player position (but still restrict to warp outside border)?

**Comment by LemADEC** [comment]
World Borders are needed to integrate the planets into the global star map with space and hyperspace.
Creative players can already go outside the mod's world border, if for whatever reason something got lost there.

In terms of performance, chances are WarpDrive is faster than plugins by nature, but also because it'll prevent living entities from spawning outside the world border.

When using plugins with MCPC/Cauldron/Thermos/etc., if we remove player world border from the mod, than server admins need to synchronize plugin configuration with the star map design. That's added work with risk of error.
What would be the added value for that?

**Comment by Sirse** [comment]
Maybe add value and implement API method to override WarpDrive WB values? For now I'm using Ultramine Core (MCForge with significant performance tweaks), they have integrated pregen and worldborder functionality (also disable mobspawn outside the border).

**Comment by LemADEC** [comment]
My question is: what is the added value for doing that change?
I only see complications, no benefits.

**Comment by LemADEC** [comment]
Any answers on this?

**Comment by StargateMC** [comment]
The only benefit of WB over WD borders is using dynmap your borders appear.... but it's a huge amount of effort to sync the borders of a large number of worlds when you already have this info in the warpdrive mod.

I ditched world border not long after using WD.

**Comment by LemADEC** [comment]
Thanks for the update, I understand we've no valid reason to fully disable WB in WD, hence closing
