### ISSUE TITLE
Update Radar LUA API for clarity

### ISSUE THREAD

**Issue by Sirse** [LemADEC/WarpDrive#348]
That method returns ship core coords twice:

https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/block/movement/TileEntityShipController.java#L416

**Comment by LemADEC** [comment]
The position method returns 2 sets of coordinates which are always the same except for the radar were the second set is 'universal' (i.e. relative to your current galaxy).
Since the ship controller actually returns the Ship core coordinates, there's an override in that class of what's already defined in TileEntityAbstractInterfaced.

The idea is to always return all 7 parameters to simplify LUA code, so you always have something to work with. An alternative would be to return 3 parameters unless the Geolocalization upgrade is installed, which currently only applies to the radar.
In practice it's more confusing than anything, and it doesn't follow the our LUA naming convention so I'm tempted to make 2 separate methods:
```lua
celestialName, x, y, z = getLocalPosition()
galaxyName, celestialName, x, y, z = getUniversalPosition()
```
First one is always available, second one requires an upgrade.

Any thoughts on that?

**Comment by LemADEC** [comment]
Updated proposal for 1.12.2:
- universal position is deprecated in favor of global position which is more explicit

- position() is replaced by getLocalPosition() on all tile entities
```lua
-- return position in current world, same as minimap
x, y, z = getLocalPosition()
```

- radar gets new methods when optical sensors are installed
```lua
-- return position inside the galaxy (only valid while in a registered dimension)
isValid, galaxyName, x, y, z, celestialName = getGlobalPosition()
-- return position inside the orbiting planet (only valid while in orbit)
isValid, celestialName, x, y, z = getLandingPosition()
-- return position in the orbit of current planet (only valid while landed)
isValid, celestialName, x, y, z = getOrbitingPosition()
```
