### ISSUE TITLE
Feature request:Fine tune warping and a on/off warp bubble button

### ISSUE THREAD

**Issue by TitaneerYeager** [LemADEC/WarpDrive#368]
Ok.
Ships must be smaller than 1200 blocks to enter a planet. They must be larger than 3000 blocks to enter hyperspace. This is completely understandable, however it removes the possibility of all-purpose spaceships.
What I am suggesting is that a new ship ability is added, being the ability to turn on and off it's warp bubble. This will allow a smaller ship to enter the bigger ship's warp bubble(when off), then the smaller ship's warp bubble gets turned off, then the larger ship's warp bubble gets turned back on to allow warping, taking the little ship along with it.
In order to dock in the larger space craft, another ability would need to be added, which is probably the hard part. Fine tune warping.  You know, like warping only one block at a time or seven blocks to not crash into the large ship. This is not necessary, just extremely helpful. (You could warp forward or backward 100blocks then the opposite way 99 blocks etc.)
If a warp bubble would get turned off in hyperspace, the ship should exceedingly and violently explode, then suck all the blocks in and destroy them, leaving any entity to suffocate. This would prevent a ship too small for hyperspace to become un-docked in hyperspace, but it would also not allow a large enough ship to un-dock in hyper space, UNLESS someone is there to activate the smaller ship's warp bubble QUICKLY. IF someone manages to successfully un-dock and turn on a too small ship's warp bubble in hyperspace, the ship should still violently explode and then implode.
Thank you for taking the time to look at this(and hopefully consider it).

**Comment by LemADEC** [comment]
The game engine prevents to jump smaller distances than the ship size. Consequences involve entity suffocation and duplication bugs, in the best cases.
Ship controller scripts are provided to players so they can make their own. Up to them to add an auto-docking procedure, an auto-jump to long range target or a probe (jump ship, radar ping, repeat), etc.

When carrying smaller ships around, on 1.7.10, you need to turn off your 'shuttle' ships by holding Ctrl-T (CC) or Ctrl-C (OC). Eventually, it'll be a menu option.

Ship explosion in case of basic jump is a bit extreme considering those ships are fairly expensive to assemble. I prefer a softer version so players can learn without losing everything. Something more along the path of:
1- you can't move a ship in hyperspace without an hyperdrive
2- exiting the warp bubble is deadly
3- over time, ship decays if they can't sustain their warp bubbles

Having a docking ship raises the question of alignments since different ships have different shape, size and core position. The basic fix is to have docking blocks on both ships that would align/bridge to each other. That doesn't fix the sizing issue, and the ship collisions that would comes from it...

**Comment by TitaneerYeager** [comment]
I understand about the small jumps. Could it be possible that to make a small jump, the ship would warp a entered direction, then back a certain amount of extra blocks or minus a certain amount of blocks? I know this can be done manually by the player, but that takes the time of two warps(warp core cooling, entering movement, and warp core warming up to do the jump). 
So you are saying there is a way to turn off ship core already? CC being computer craft and OC being open computers, correct? EDIT:I tested it and thank you so much! This works!
I understand 1 & 2, but I am not exactly sure what 3 means. I am pretty sure it means if there is not enough energy to the ship core, but does it also include when not warping? Meaning, when the ship is just sitting there, will the ship still decay if there is not enough energy to the ship core?
My idea seems to be currently possible, but I thought you had to break the ship core to disable it. That would be annoying that every time you wanted to use the pod you would have to re-place the ship core & possibly re-enter the dimensions.
When I mean docking, I mean that the larger ship must be purposely BUILT to accept the little ship, eliminating the sizing issue, and if the person did not build either the larger or smaller ship correctly with each other, well, then the player will have a crash on his hands and will hopefully be more careful next time.

**Comment by LemADEC** [comment]
Again, the mod uses LUA programmed computers so players do their improvements.
The objective is to require energy to stay in hyperspace.
Docking should be also doable with NPC builds like a space station of sort.

**Comment by LemADEC** [comment]
Not answer for 10 days, assuming all cleared up.
