### ISSUE TITLE
Can't turn the end into space, dimension already registered

### ISSUE THREAD

**Issue by Mizhok** [LemADEC/WarpDrive#394]
I wanted to change it so that instead of going to Space when you warp up high enough, you go into the end. I tried to do this by changing the SolarSystem's dimension id to 1.

I also removed Pluto but the game still crashed saying that the end is already registered. 

https://pastebin.com/Y2nixYtb : config file

https://pastebin.com/3HiFjJmn : crash report

**Comment by LemADEC** [comment]
That's an interesting idea.

Here a few things to consider through:
1- in your hierarchy, below hyperspace there needs to be a space dimension.
2- a space dimension is registered and generated by WarpDrive. So here, you're telling dim1 should be registered by the mod as space, that won't work...
3- due to Vanilla hardcoded stuff, you can't exit the end dimension or portal as a player without being forced to the world spawn.

To do what you're trying to achieve, check how the nether is declared inside the earth tag and do the same with the end containing the earth. Do not remove space. In your lore, you could keep The End as big as the space dimension if you like, and have planet below the end instead of below space, but whatever happens, space needs to be below hyperspace.
To prevent weird teleportation issue, you want to replace TheEnd with a modded dimension with a single biome, the end one. You can typically do that with JustEnoughDimensions, there's plenty example on how to create dimensions, check the dev's discord.

**Comment by LemADEC** [comment]
Any update on this?

**Comment by LemADEC** [comment]
No update, assuming fixed
