### ISSUE TITLE
Forcefield Colors 

### ISSUE THREAD

**Issue by Julienc249** [LemADEC/WarpDrive#398]
For some reason no matter what frequency I try, tuning fork or custom, I can't get the forcefield to change color. Normally this wouldn't really be a problem because it doesn't affect functionality but I like to be able to see through my shields. The basic reddish color is not very good for that. Alternatively, maybe alter the texture so that they are a little more see through in the future?

**Comment by LemADEC** [comment]
All colors share the same transparency level. The latest was increased on 1.12.2.

Beam frequencies are scaling up to 65000. It's rainbow from 0 to 60000, then a hex color coding above that, something like: `60000 + 5000 / 4096 * (red + green * 16 + blue * 256)` with red, green & blue going from 0 to 15.

**Comment by Julienc249** [comment]
Ok, thanks a lot for the information, I am going to try that!

**Comment by Julienc249** [comment]
For some reason, I can't get this to work, I am probably doing something wrong. How would I get a blue color for example?

**Comment by LemADEC** [comment]
The beam frequency colors I gave are for the laser and particle effects.
The force field blocks are changing with a different formula to give the dye color, something like: `16 * beamFrequency / 65000`. So 55513 makes it Magenta (13) color.
That being said, there's bug that prevent changing the block color on 1.12..2 that'll be fixed with next update.

**Comment by Julienc249** [comment]
Ok, thank you very much for clearing all of that up!! Good luck, this is one of the best mods I have played with.
