### ISSUE TITLE
IC2 Classic integration

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#464]
**Is your feature request related to a problem? Please describe.**
IC2 Classic machines after warp looses connection to energy network.

**Describe the solution you'd like**
Add integration like for other tech mods.

**Additional context**
Tested on:  
WarpDrive 1.5.15 Beta for 1.12.2
IC2Classic 1.12-1.5.5

**Comment by LemADEC** [comment]
IC2Classic shares same modid as IC2Experimental, but internal structure is quite different, while item registry name have no relation whatsoever.
So far, in addition to energy network requiring a chunk reloading, I've seen issues in Laser tree farm (rubber wood, resin), breathing (compressed air, empty cell), and probably recipes.
I see no verbose/debug option for the energy net, let's hope it's an easy fix, otherwise it'll have to wait.

**Comment by NCrashed** [comment]
Thank you!
