### ISSUE TITLE
If dynamic surroundings installed, I can hear the sounds of nature.

### ISSUE THREAD

**Issue by Exzept1on** [LemADEC/WarpDrive#488]
**Describe the bug**
When Dynamic Surroundings is installed and when I go to space, I hear the sounds of the biome.

**To Reproduce**
1.  Install WarpDrive
2.  Install Dynamic Surroundings
3.  Jump to Space
4.  Hear biome sounds(water breeze or birds songs)

**Expected behavior**
I can hear the sounds of nature, even though I'm in space.

**Screenshots** [Biome river in space XD]
![2021-04-20_19 35 56](https://user-images.githubusercontent.com/52341158/115405033-12027d80-a218-11eb-9193-69a81fec3469.png)

**Logs**
Not needed

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.20 1.12.2
-   Forge version: 2855
-   Modpack name/version: TerraFirmaGreg
-   Dynamic Surroundings: 3.6.2.1

**Additional context**
Not needed

**Comment by Exzept1on** [comment]
Since Dynamic Surroundings reproduces its sounds in certain biomes, I would suggest making a biome with the name **space** in the dimension of the **space**(and hyperspace). Because now I saw that even when I'm in space, the biome doesn't change. For example, I was in Plains, teleported into space, and still the biome remained Plains.

**Comment by LemADEC** [comment]
The space dimension is exclusively made with the space biome already by design. If you still hear sounds, there's probably another mod messing around with biomes like notably NotEnoughIds.
There was also discussion with having per dimensions settings in Dynamic Surroundings to account for that, notably to remove the altimetric fog back in the days.
Either way, it's not a WarpDrive issue :).

**Comment by Exzept1on** [comment]
Its JustEnoughIds issue, oh sorry then.
