### ISSUE TITLE
Consider block metadata in Dictionary configuration

### ISSUE THREAD

**Issue by kolamp** [LemADEC/WarpDrive#516]
**Is your feature request related to a problem? Please describe.**
The Laser mining machine treats ExtraPlanets' stones, e.g. Mercury stone, as ores. This is due to the fact that the same block name is used for stones as well as different ores, just the metadata changes. The warpdrive dictionary configuration however does not consider the metadata, if I read the code correctly.

**Describe the solution you'd like**
Consider block metadata in the Dictionary configuration, maybe similar to how it is done already in the DataFixer configuration file. As a bonus, one could then also define special behaviour for variants of blocks/items/entities only.

**Describe alternatives you've considered**
Make all other mod authors use proper block names....

**Additional context**
If you want to reproduce, here are the mods I used:
- Minecraft version 1.12.2
- Forge version 14.23.5.2855
- [extraplanets](https://www.curseforge.com/minecraft/mc-mods/extraplanets) version 0.7.3
- [MJRLegendsLib](https://www.curseforge.com/minecraft/mc-mods/mjrlegendslib) version 1.2.1
- [Galacticraft](https://micdoodle8.com/mods/galacticraft/downloads) version 4.0.2.280
- warpdrive version 1.5.25

**Comment by LemADEC** [comment]
I'm only aware of a 1 other edge use-case for that due to ImmersiveEngineering mixing unrelated blocks behind the same blockId.    
With ExtraPlanets, those 2 mods are clearly doing it wrong in terms of compatibility.  
Implementing support for those implies a lot of changes in WarpDrive, including across its API with other mods. It wasn't considered worth it during the 1.10+ port, and it's still isn't on 1.12.
That being said, this is fixed in the 1.15+ port of WarpDrive, so it'll be fixed eventually.

**Comment by kolamp** [comment]
I see, thanks for the clarification.

I was thinking about overloading dictionary entries/lookups, making the additional metadata argument optional. That way, no changes to the API or even other code accessing the dictionary within WarpDrive would be necessary.

I am aware though, that this is low priority.
