### ISSUE TITLE
OpenComputers PowerConverter stack overflow with AppliedEnergistics2 API

### ISSUE THREAD

**Issue by masterblaster221** [LemADEC/WarpDrive#520]
**Describe the bug**

**To Reproduce**
1.  try to go in to hyperspace then crash

**Expected behavior**
enter hyperspace

**Logs**
https://gist.github.com/masterblaster221/c0c130d30e397eaecdd029234bb41481

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.27
-   Forge version: 14.23.5.2860
-   Modpack name/version: 1.12.2
-   Other notable mods & version:

**Comment by masterblaster221** [comment]
lol I sent the wrong crash log I edited it.

**Comment by LemADEC** [comment]
Crash shows a stack overflow due to recursive calls between an OpenComputers PowerConverter and AppliedEnergistics2 API.
Sounds like someone tried to power an OpenComputers PowerConverter through AE2.
Both of those mods aren't so good for power, so it's a double recipe for failure, right there.
More importantly, I don't see how any of these is related to WarpDrive.

For the record, IC2 and Mekanism are known for their recurrent issues during chunk loading and working in other dimensions, they still behave better for power than above setup.
Consider using ThermalDynamics or EnderIO for a more robust power transportation option.

**Comment by masterblaster221** [comment]
Thank you very much I will give it a try.
I appreciate the help.
