### ISSUE TITLE
Congratulations 

### ISSUE THREAD

**Issue by sergeyivanov164** [LemADEC/WarpDrive#540]
Congratulations on behalf of the development team of the Russian-language server "Evermine" on receiving the Ig Nobel Prize for the most masterpiece solution in the mod code:

![image-18](https://user-images.githubusercontent.com/102871098/226664465-38022d5b-80b7-4b5f-b4d1-280c4df4e3f8.png)

P. s. Why did it have to be done at all? This breaks many mods. I advise you to change it somehow

**Comment by LemADEC** [comment]
Blast resistance impacts PvP features like explosives, weapons and assimilated. Many mods use exaggerated values that breaks PvP aspects.
This code reuse the same logic other major mods do to address the very same problem. WarpDrive is a bit smarter in that it's actually exposing a configuration value for it and logs the changes so that modpack developers are actually aware of what is going on.
That being said, there's an issue template it's not optional, use it.
