### ISSUE TITLE
Add particle effects to warp

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#55]
Would look cooler than just having the ship disappear

**Comment by YuRaNnNzZZ** [comment]
Like this one?
![](http://cs622519.vk.me/v622519268/46dd4/dVb5JdWC4O0.jpg)
(this screenshot is from old mod Aerospace)

**Comment by TheNumenorean** [comment]
That looks awesome

**Comment by LemADEC** [comment]
I've already seen this picture. Any chance you've more? the original mod maybe?

**Comment by LemADEC** [comment]
I did a bit of digging and it appears the Aerospace mod still has a wiki online here: http://ru.aerospace.wikia.com/wiki/Aerospace_%D0%B2%D0%B8%D0%BA%D0%B8
The build server and launcher are no longer available. The jump procedure was quite different from what I understood.
Here another view on the effect seen during jump:
![before](http://i.imgur.com/XWiZ9.jpg)
![effect](http://i.imgur.com/50Dn1.jpg)
![after](http://i.imgur.com/tUxd0.png)

That shouldn't be too hard to recreate.

**Comment by CaptainMegavolt** [comment]
That looks pretty cool, although when I thought of particles for warping, I thought more along the lines of a sort of neon-blue streak encompassing the ship and stretching across space left behind by the ship in the wake of the jump (like from a Star Trek Next Generation warp drive pod). On that subject, it would be neat to have ships require external warp field emitters of some sort, along with some sort of warp field mechanics as a new thing for players to manage.

**Comment by LemADEC** [comment]
Do you have a picture of that effect?

**Comment by CaptainMegavolt** [comment]
It's not something I've seen in a minecraft mod before, but I can give you a non-minecraft image of roughly whay I'm thinking.
![Engine Trails](http://media.moddb.com/images/mods/1/6/5393/27843.jpg)
![Stargate Universe Destiny](http://www.stargate-project.de/stargate/images/technologien/ftlantrieb_2.jpg)
Something like a cross between the trails from these two images, with a long beam left behind the ship, slowly fading away in the wake of the warp jump, but with a cocoon of energy appearing around the ship as the warp drive is warming up, and lingering around the ship for a couple seconds after the jump. Also, I think that the color should be customizable, so that, say, on a faction war server, each faction could have distinct jump trails.

In addition, you could have particles/animations for jumping to hyperspace. I was thinking something like the hyperspace animations from Stargate (or maybe homeworld), where a "hyperspace window" opens in front of the ship, then the ship goes through it. For the purposes of minecraft, until the fly-by update, the window effect could swallow the ship, instead of the ship moving into it.

**Comment by LemADEC** [comment]
Already done last year, closing
